### ISSUE TITLE
Security Flaw

### ISSUE THREAD

**Issue by Thunder33345** [BoxOfDevs/Functions#11]
### Brief description

Insecure encryption

As someone who like to break stuff for fun the said encryption is very easy to break,

even tho it is impossible to retrieve the said password due to how it have been converted into numbers like how you cant find out exactly what made 100 but you could guess it is 50x2 or 10x10 etc it also limit the strength itself since regardless how long my password is, i will get around so many length due to how hash alwayls have some estimated lenght

it is possible to decode the encrypted content without much computing power, there is a down fall to this by turning the password into numbers first then messing them up will make it very easy to brute force (mind you i am no cryptographer)

which i advise to not advertise your encryption feature as a strong encryption, I know this is not really something of major concern to the team but i just want to point it out

### steps:
is to reverse engineer the encrypt part which uncover all it did was splitting each string into a array

then foreach strings turn them into number + a hard coded 23 + the number resulted by the hash of the password itself 

which lead me to the realization of why not trying all iterations of numbers with a good success and easy brute forcing 

### as for how to fix it:
i think other then using something like a true encryption like AES there not much ways around it
OR use a longer hash that generates a longer number thrust taking more iterations for the attacker (and dont hardcode the long number, just make it so it is PRONE to happen hard coding makes attacker skip the lower part when they know the number dont starts there)

As for the source code it's self it will be released some time latter, HOPEFULLY when this is resolved or ignored as not fixing even tho by reading my feedback it is already given info to make your own version

if you really do not believe me you could upload a encrypted .func i will get back to you when i can with the un-encrypted (getting password is not possible like i said earlier)

**Comment by Ad5001** [comment]
I see... I'm thinking of a way to do it properly. Will do some tries thought I'm not an encryption master. Not using a number but right coding the password into the code. So brute forcing would be harder.

For the hardcoded 23, it's to be not modifiable in a .func format. But it will be remove with the new algo.

**Comment by Thunder33345** [comment]
there some examples on http://aesencryption.net
just DO NOT (NEVER) use mcrypt it is obsulent and outdated and pending removal use something like openssl extention
like example fetch the encrypted content and see if it can be decrypted with said pwd, if it could means it should work other wise tell user to re input password

you also should start using encryption version headers so things dont get messy when changing around

**Comment by Ad5001** [comment]
Should be better now.
And about the encryption header, I thougth about it but I forgot to add it.

Thought wondering about using public encryption instead of fully made for functions but I'm quite not sure for now.

**Comment by Thunder33345** [comment]
i recommend just do a quick encryption header push before things get too far
just notice your new push, will attempt to break it tomorrow when possible
but i doubt it if it will hold on for too long
also security throught obscurity is not a good idea here when using open source

**Comment by Ad5001** [comment]
True... Will see about this tomorrow too.

**Comment by Thunder33345** [comment]
well this have definitely proven to take more effort but what i know for now is, there only 32640 possible combinations due to how ord only works with ASCII characters which may impact other langue users ex chinese etc and there only 255 character space multiplied by the key of 128
the * $i part was somewhat of a fail attempt since it just changes the key relative toward the key index position, so does trying to do the key backwards which just means i should make my bruteforce key gen backwards

the only problem is... generating all 32640 possible combinations of them

a trailhead would to be something similar to https://gist.github.com/Thunder33345/195444d21cca9b0e53850b0f8968ed99 but not nested in 128 foreach loop, hopefully if i could figure a better algorithm for it

**Comment by Ad5001** [comment]
So the whole problem is ASCII? Wow I learnt much by doing som researches on the internet. Now it'll work with Unicode chars code points. That should be better.

**Comment by remotevase** [comment]
Wow

**Comment by Thunder33345** [comment]
since the original version is fixed, here is the source code for first encrypt version
https://gist.github.com/Thunder33345/c409b1398eaefa3cdd4587dd0537be32

**Comment by Ad5001** [comment]
Thought, remember that, first, the password is encrypted with an sha512 algorithm so there would be in ANSII .

**Comment by Thunder33345** [comment]
well yes, but what about the code itself?
like if it have non ANSII characters that uses foreign languages? the chr ord shift would transform them into gibberish i believe
after testing it shows somehow it(or i meant SOME) is not affected 

also back to main topic, another possible way is http://stackoverflow.com/questions/19067556/php-algorithm-to-generate-all-combinations-of-a-specific-size-from-a-single-set but storing them into arrays then recall and test them one by one just wont work due to the nature of how big it can get

so now i am thinking of something similar toward 1st mentioned link, or something else more compact or with a callback of some sort

**Comment by Ad5001** [comment]
In the password? As I said, the password is encrypted as sha512.

**Comment by Thunder33345** [comment]
no i meant content like the actual commands functions itself not the password itself

**Comment by Ad5001** [comment]
I changed locally the serialization to JSON so that those characters will be base by their Unicode Character.

**Comment by Ad5001** [comment]
Well, will change the Unicode plage which I can't get to work using pack. Back to ANSII and JSON. Will never pass to other chars than ANSII.

**Comment by Ad5001** [comment]
Oh nvm will keep unicode, it's just me that forgot to change a value when adding the encryption header.

EDIT: Can't still get pack to do what I want. Switch back to ansii as suggested before.

**Comment by Thunder33345** [comment]
updated the script for 2nd version, https://gist.github.com/Thunder33345/c409b1398eaefa3cdd4587dd0537be32
just the time it took for it to generate a full chain proven to take quite a bit of time so i will say it is semi secure
it will only break if someone actually have legit reason to rent a high end VPS just to break the script for whatever motivation

**Comment by Thunder33345** [comment]
i dont know if i want to attempt to break the newer version
also for password header, i think it shouldnt follow plugin version BUT encryption scheme version

**Comment by Ad5001** [comment]
Depends if we'll use this encryption for other things. Butthanks already for the time you passed helping figuring out how to make a better encryption :).

**Comment by remotevase** [comment]
I'm just gonna unwatch this, because I dont even understand half of it XD
