### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Leejit** [BoxOfDevs/Functions#12]
If functions are permissable, meaning a given permission to use each function, then how would I go about giving/taking permissions for each function ?

unless there is a way to check this in the function itself, please explain as not enough examples were given for me to figure this out on my own.

Thank you.

**Comment by lavender-sys** [comment]
You would use something such as PurePerms for adding/removing perms.

**Comment by AvgZing** [comment]
Solved?

**Comment by dragonwocky** [comment]
I guess so....
