### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by BlackZeroPM** [BoxOfDevs/Functions#13]
### Steps to reproduce

1. ...
2. ...
3. ...

### Server Information
* Functions Version: From PMMP Forums 
* Software Version: I dont know.  
* Server OS: 

### CrashDumps/Errors
```
Paste your CrashDump or error by replacing this text (DON'T delete the backticks!)
```

**Comment by AvgZing** [comment]
Useless stuff, incorrect template, please fill out all of the fields

**Comment by HimbeersaftLP** [comment]
Seriously @BlackZeroPM? Do you think we can magically find out your problem (the one with the plugin, not the obvious one with your brain)...

**Comment by AvgZing** [comment]
There is no chance of a snowflake in hell that we will find either of those problems...
