### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AyyItzJ4y** [BoxOfDevs/Functions#15]
hi

**Comment by HimbeersaftLP** [comment]
Orignal issue content before you edited it:
![Original issue screenshot](https://i.imgur.com/Lio2bdS.jpg)

If you want a .phar of this plugin: https://poggit.pmmp.io/ci/BoxOfDevs/Functions/

If you want to complain about pmt.mcpe.fun: https://github.com/pmt-mcpe-fun/web.app
