### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ghost** [BoxOfDevs/Functions#18]
Please update the plugin for 3.2.0 with new API documentation

**Comment by ghost** [comment]
please

**Comment by dragonwocky** [comment]
Noted. I'll bring it up with the rest of the team. It's on our todo list already, though, anyway.

**Comment by TheDragonRing** [comment]
test (will be deleted)

**Comment by TheDragonRing** [comment]
test (will be deleted)

**Comment by Ifera** [comment]
@georgianYT what exactly are the errors cause I just tested it and its working fine

**Comment by Ifera** [comment]
Requesting to close since no information provided also the plugin is working fine
