### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheWalkingDrift** [BoxOfDevs/Functions#19]
I've got Pocketmine Version 3.8.2 and the Plugin Version 1.2.1.

Thus is the problem:

atal error: Declaration of Ad5001\Functions\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar:///storage/emulated/0/PocketMine-MP/plugins/Functions_v1.2.1.phar/src/Ad5001/Functions/Main.php on line 15

**Comment by TheWalkingDrift** [comment]
> I've got Pocketmine Version 3.8.2 and the Plugin Version 1.2.1.
> 
> Thus is the problem:
> 
> atal error: Declaration of Ad5001\Functions\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar:///storage/emulated/0/PocketMine-MP/plugins/Functions_v1.2.1.phar/src/Ad5001/Functions/Main.php on line 15

**Comment by Ifera** [comment]
https://poggit.pmmp.io/ci/BoxOfDevs/Functions/Functions

Download latest version from there. You are using an old (too old) version.

**Comment by InspectorGadget** [comment]
Indeed. Please download the latest version of Functions from Poggit.
