### ISSUE TITLE
still unknown command when running custom commands

### ISSUE THREAD

**Issue by kabluinc** [BoxOfDevs/Functions#4]
So I did /function create lobby 
Then did /function ac lobby warp lobby
I set perms for func.use.lobby and func.use.default

Still says unknown command when doing /lobby or ./lobby

**Comment by Ad5001** [comment]
Hmmm.... Any message in the console?

**Comment by kabluinc** [comment]
Nope. Nothing in console. Just none of the commands created can ever be run. Just shows unknown command. Worked fine in 0.15

**Comment by lavender-sys** [comment]
It's probably something with 0.16 then.

**Comment by Ad5001** [comment]
Looks like PlayerCommandPreprocessEvent is no longer fired.

**Comment by kabluinc** [comment]
I did one thing as a test. I added one of the functions I create (lobby) to the plugin.yml like this

--- 
 name: Functions 
 author: Ad5001 
 version: "1.0" 
 api: 
 - 1.14.0 
 main: Ad5001\Functions\Main 
 commands:  
   function: 
      description: "Create, manage and remove functions with this command" 
      usage: "/function <sub-command> <function> parameters..." 
      permission: func.command.function 
  **lobby:
      description: "Go to servers lobby"
      usage: "/lobby2
      permission: func.command.lobby**
 permissions: 
    func.command.function: 
      default: op 
      description: "Create, manage and remove functions with this command" 
    func.use.default: 
      default: true 
      description: "Defines users permission to use a specific function if permission node func.use.functionname is not set" 
     **func.command.lobby: 
      default: true
      description: "go to servers lobby"** 

After doing this the command /warp lobby that was added to the function "lobby" worked and I was able to run /lobby fine.

Adding all the functions created to the plugin.yml makes them work if not it just says unknown command

**Comment by Ad5001** [comment]
I see... It's command registering for 0.16.

**Comment by kabluinc** [comment]
Can this be fixed?

**Comment by Ad5001** [comment]
it could, but rn, I have some IRL things that makes me reaaaalllyyy buzy so coding & bug fixing is not my current priority.

**Comment by Ad5001** [comment]
Fixed.
