### ISSUE TITLE
ImagicalMine? With PocketMine back, ImagicalMine is dead...

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/Functions#5]
This plugin is not for ImagicalMine it should be for PocketMine

**Comment by Ad5001** [comment]
Agree, but looks like I cannot change it.

**Comment by remotevase** [comment]
Yup... Only @TheDragonRing

**Comment by lavender-sys** [comment]
ImagicalMine is basically dead. When it went to @Inactive-to-Reactive it died. So yeah, this should be for PocketMine.

**Comment by dragonwocky** [comment]
yeah true. I'm planing to move to self-hosted GitLab -> once I do everything will be changed and you'll get more perms... sorry about that.

**Comment by lavender-sys** [comment]
You'll need to help me get started with gitlab.

**Comment by dragonwocky** [comment]
sure. I think it'll work slightly differently to gitlab.com since it'll be self-hosted on our website 😋

**Comment by lavender-sys** [comment]
Does gitlab run PHP?

**Comment by dragonwocky** [comment]
what do you mean?

**Comment by Ad5001** [comment]
I think he asks if Gitlab run some PHP code on it's website OR if Gitlab is made with PHP

**Comment by dragonwocky** [comment]
ohhhhh.... I'm not sure

**Comment by HimbeersaftLP** [comment]
@TheDragonRing, you are back!

**Comment by remotevase** [comment]
yup! he graduated and now has the summer off! Speaking of which @TheDragonRing check your twitter DMS

**Comment by dragonwocky** [comment]
Yup, I'm finally back! On Wednesday I'm beginning work on the _new_ BoxOfDevs Team :grinning:

**Comment by Ad5001** [comment]
So issue is closed
