### ISSUE TITLE
Tesserect (Probably low spelled)

### ISSUE THREAD

**Issue by samp-pinch** [BoxOfDevs/Functions#6]
# Brief description (why it is an issue)

# Steps to reproduce (how can anyone reproduce the issue)

# Expected result (what do you want to happen)

# Actual result (what actually happens)

# OS Infomation

Functions version(Commit number or link to where you got your .phar): 
Software Version: 
OS Version: Android

# Logs/Errors
CRASH DUMP:
https://www.sendspace.com/file/4ekokc

P.S Tesserect is new name of ImagicalMine

**Comment by samp-pinch** [comment]
Tesserect is best 1.0.0 solution...so...
Only tesserect work fine 💯

**Comment by samp-pinch** [comment]
And 1 question (I know this is not place for that,but I also know to I van only here ask,so..)
Can u make Broadcaster like LEET? (/bc add/list/remove,and custom time like on leet (/bc add))

**Comment by Ad5001** [comment]
Issue fixed..
About the new plugin, it'll be when members will be active again.

**Comment by samp-pinch** [comment]
@Ad5001 I'll reclam you on my channel,im pocketminer.:D

**Comment by samp-pinch** [comment]
ADVERTISE*
