### ISSUE TITLE
READ FULL,THAN CLOSE PLEASE

### ISSUE THREAD

**Issue by samp-pinch** [BoxOfDevs/Functions#7]
Close this immediately,but PLEASE read!
I cannot open (Don't know how) new pull request,so I'll type here:
@Ad5001 Please add something like this (example from LEET.CC-TapToDo)
So lets begin what I want.(low at english)
/function create PvP
/function ac PvP tp X Y Z
And when player execute /pvp cmd,he/she to that coords even if no permission (example Guest without perm,can use /pvp,like /tp %p X Y Z%pow)
Translations: Please add some like %p %pow %op,any just to can do it

**Comment by Ad5001** [comment]
Add {op} to your command for this.
And if you want the command to be executed from the console, add a {console}

**Comment by samp-pinch** [comment]
AWWW THX <3

**Comment by samp-pinch** [comment]
And are is leet up to date? @Ad5001

**Comment by lavender-sys** [comment]
@NemanjaMAX From what I've heard, leet has not updated. Create a thread at forum.leet.cc and tell them to get a new build from https://github.com/BoxOfDevs/Functions

**Comment by Ad5001** [comment]
I wasn't knowing that leet was using our plugin. Did they atleast credited us?

**Comment by dragonwocky** [comment]
Did anyone know that leet was using our plugin?

**Comment by HimbeersaftLP** [comment]
I didn't know too xD

**Comment by moskadev** [comment]
Ad, tu croyais sérieusement que LEET allait venir te dire qu'ils prenaient votre plugin ? C'est des voleurs, et ils disent après que "des développeurs nous ont concocté de nouveaux plugins pour les serveurs LEET.CC !".

**Comment by HimbeersaftLP** [comment]
Google Translation of the post above:
> Ad, you thought seriously that LEET would come and tell you that they were taking your plugin? They are thieves, and they say after that "developers have concocted new plugins for the servers LEET.CC!".

**Comment by Vaults1** [comment]
I would have accepted LEET using it if they ask. Since they didn't, I recommend we ask them to remove it.

**Comment by Ad5001** [comment]
@SuperMaXAleX Well, not really but I haven't seen any person except now telling us leet took our plugin.
The new license should make the difference.

**Comment by remotevase** [comment]
DMCA THEM!

**Comment by dragonwocky** [comment]
Same @Ultie0
